image: debian:latest

variables:
  IMAGE_NAME: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME"
  AWS_REGION: "us-east-1"  # as an example
  AWS_CLUSTER: "ecs-cluster"
  AWS_SERVICE: "datetime-service"
  AWS_TASK_DEFINITION: "your-task-definition"

stages:
  - build
  - deploy

build-image:
  stage: build
  script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  image: amazon/aws-cli
  script:
    - aws ecs update-service --cluster $AWS_CLUSTER --service $AWS_SERVICE --force-new-deployment
  only:
    - main  # Deploy only when pushing to main branch

